name: reuse-tester
on: 
  workflow_call:
    inputs:
      dotnet-version:
        description: 'The .NET SDK version to use for testing'
        type: string
        required: true
jobs:
  test:
    runs-on:
      - codebuild-pulse-application-pipeline-stack-pulse-powerbi-pullrequest-${{ github.run_id }}-${{ github.run_attempt }}
      
    steps:
      - name: Publish a Echo
        run: echo "Tests for this completed successfully for .NET SDK version ${{ inputs.dotnet-version }} on run ${{ github.run_id }} and attempt ${{ github.run_attempt }}"

      - name: Fetch Runner Registration Token
        run: |
          curl --request POST \
            --url 'https://github.siemens.cloud/api/v3/repos/xuan-thanh-tran/WebApiTest/actions/runners/registration-token' \
            --header 'accept: application/vnd.github.v3+json' \
            --header 'authorization: token ${{ secrets.GHE_PAT_TOKEN }}'