name: CI-Test-Workflow
on:
    push:
        branches:
            - main
jobs:
    test:
        uses: ./.github/workflows/reuse_tester.yaml
        with:
            dotnet-version: '10.0'
         
            